src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $content;

    /**
     * @ORM\Column(type="integer")
     */
    private $note;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\product", inversedBy="comments")
     */
    private $product;

    /**
     * @ORM\Column(type="datetime")
     */
    private $published_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(?string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getProduct(): ?product
    {
        return $this->product;
    }

    public function setProduct(?product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeInterface
    {
        return $this->published_at;
    }

    public function setPublishedAt(\DateTimeInterface $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }
}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Entity\EventSubs;
use App\Form\EventSubsType;
use App\Form\MessageMeType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\{Product,PackOffer,Subscription,Event,MessageMe,EventPassed};

class ShopController extends AbstractController
{
    /**
     * @Route("/", name="shop.home.index")
     */
    public function index()
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findTopProduct();
        $offers = $this->getDoctrine()->getRepository(PackOffer::class)->findAllHomeView();
        $events = $this->getDoctrine()->getRepository(Event::class)->findPublished();

        
        $subscriber = new EventSubs();
        
        $form = $this->createForm(EventSubsType::class,$subscriber);

        //Pour afficher un seul événement à la fois sur la page d'accueil
        isset($events[0]) ? $event = $events[0] : $event = null;
        isset($products[0]) ? $product = $products[0] : $product = null;

        $i = 0;

        //Pour limiter à 2 le nombre d'offres sur la page d'accueil
        foreach($offers as $offer){
            if($i < 2){
                $published_offers[] = $offer;
            }
            $i++;          
        }
        
        return $this->render('shop/index.html.twig', [
            'product' => $product,
            'offers' => $offers,
            'event' => $event,
            'form'=> $form->createView()
        ]);
    }

    /**
     * @Route("/products", name="shop.list.products")
     */
    public function listProducts(){
        $products = $this->getDoctrine()->getRepository(Product::class)->findPublished();

        return $this->render('shop/products.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * @Route("/offers", name="shop.list.offers")
     */
    public function listOffers(){
        $pack_offers = $this->getDoctrine()->getRepository(PackOffer::class)->findPublished();
        $subscriptions = $this->getDoctrine()->getRepository(Subscription::class)->findPublished();

        return $this->render('shop/offers.html.twig', [
            'pack_offers' => $pack_offers,
            'subscriptions'=> $subscriptions
        ]);
    }

    /**
     * @Route("/events", name="shop.list.events")
     */
    public function listEvents(Request $request, ObjectManager $manager){
        
        //Récupération des informations depuis la base de donnée
        $posts = $this->getDoctrine()->getRepository(EventPassed::class)->findAll();
        $events = $this->getDoctrine()->getRepository(Event::class)->findPublished();
        
        //Création et traitement du formulaire d'inscription aux événements

        $subscriber = new EventSubs();
        $data = $request->get('event_subs');
        
        $form = $this->createForm(EventSubsType::class,$subscriber);

        //récupération de l'url précédent
        $referer = $request->headers->get('referer');
     
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid() ){

            //Vérifier que l'utilisateur a bien choisi au moins un événement
            
            if(count($subscriber->getEvent()) !== 0)
            {
                $manager->persist($subscriber);
                $manager->flush();

                //redirection vers l'url précédent
                return $this->redirect($referer);
            }
            else{          
                $this->addFlash(
                    'notice_bad',
                    'Vous devez choisir au moins un événement.'
                );
            }

        }

        else if(isset($data)){

            $subscriber->setName($data['name']);
            $subscriber->setFirstName($data['first_name']);
            $subscriber->setEmail($data['email']['first']);

            if(isset($data['event'])){
                $i =0;
                foreach($data['event'] as $eventId){
                    $event = $this->getDoctrine()->getRepository(Event::Class)->findById($data['event'][$i]);
                    $subscriber->addEvent($event);
                    $i++;
                } 
            }

            try{
                
                $manager->persist($subscriber);
                $manager->flush();
            }
            catch(\Exception $e){
                $this->addFlash(
                    'notice_bad',
                    'Vous êtes déjà inscris à un événement.'
                );
            }

            //redirection vers l'url précédent
            return $this->redirect($referer);
        }


        return $this->render('shop/events.html.twig', [
            'events_passed' => $posts,
            'events' => $events,
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/articles", name="shop.list.articles")
     */
    public function listArticles(){

        return $this->render('shop/articles.html.twig', [
        ]);
    }

    /**
     * @Route("/whoweare", name="shop.show.whoweare")
     */
    public function whoWeAre(){

        return $this->render('shop/whoweare.html.twig', [
            'title' => "Qui sommes-nous ?",
        ]);
    }

    /**
     * @Route("/messageMe", name="shop.show.messageme")
     */
    public function messageMe(Request $request,\Swift_Mailer $mailer){

        $message = new MessageMe();

        $form = $this->createForm(MessageMeType::class, $message);

        $form->handleRequest($request);

        if( $form->isSubmitted() && $form-> isValid()){

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($form->getData());
            $manager->flush();

            $mail = (new \Swift_Message('Contact Email'))
                        ->setFrom($message->getEmail())
                        ->setTo('chemseddine.saada2@gmail.com')
                        ->setBody(
                                $this->renderView(
                                'emails/messageme.html.twig',
                                ['message' => $message]
                            ),
                            'text/html'
                        );

            $mailer->send($mail);

            $this->addFlash(
                'success',
                'Votre message a bien été envoyé'
            );
            return $this->redirectToRoute('shop.show.messageme');
        }
        return $this->render('shop/contact.html.twig', [
            'form' => $form->createView(),
        ]);
    }


}

src/Controller/SingleController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class SingleController extends AbstractController
{
    /**
     * @Route("/product/{slug}", name="single.show.product")
     */
    public function singleProduct($slug)
    {
        $product = $this->getDoctrine()->getRepository(Product::class)->findById($slug);

        return $this->render('shop/singles/product.html.twig', [
            'product' => $product,
        ]);
    }

    /**
     * @Route("/category/{slug}", name="single.show.category")
     */
    public function singleCategory($slug)
    {
        $category = $this->getDoctrine()->getRepository(category::class)->findById($slug);

        return $this->render('singles/category.html.twig', [
            'category' => $category,
        ]);
    }

    /**
     * @Route("/article/{slug}", name="single.show.article")
     */
    public function singleArticle($slug)
    {
        $article = $this->getDoctrine()->getRepository(Article::class)->findById($slug);

        return $this->render('singles/article.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/subscription/{slug}", name="single.show.subscription")
     */
    public function singleSubscription($slug)
    {
        $subscription = $this->getDoctrine()->getRepository(Subscription::class)->findById($slug);

        return $this->render('singles/subscription.html.twig', [
            'subscription' => $subscription,
        ]);
    }
}

templates/shop/singles/article.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

{% endblock %}

templates/shop/singles/product.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block more_style %} 
    <link rel="stylesheet" href="{{asset('web/css/body-menu.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/singleproduct-style.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/form-style.css')}}">
{% endblock %} 

{% block body %}

<!-- PRODUCT ELEMENT START -->

<div class="d-flew row">
    <!-- SLIDER START-->
    <div class="d-flex row col-5 slider-product">

        <div class="slider-show col-12 text-center">
            <img class="img-fluid" src="{{asset('/uploads/images/products/' ~ product.image1)}}" alt="{{product.description}}" id="1">
        </div>

        <div class="slider-nav">
            <div><img class="image1 slide-active" src="{{asset('/uploads/images/products/' ~ product.image1)}}" alt="{{product.description}}" id="1"></div>
            <div><img class="image2" src="{{asset('/uploads/images/products/' ~ product.image2)}}" alt="{{product.description}}" id="2"></div>
            <div><img class="image3" src="{{asset('/uploads/images/products/' ~ product.image3)}}" alt="{{product.description}}" id="3"></div>
            <div><img class="image4" src="{{asset('/uploads/images/products/' ~ product.image4)}}" alt="{{product.description}}" id="4"></div>
        </div>
        <div class="slider-arrows">
                <span class="prev-arrow"><img src="{{asset('web/img/product/arrow-top.svg')}}" alt="Flèche haut"></span>
                <span class="next-arrow"><img src="{{asset('web/img/product/arrow-bottom.svg')}}" alt="Flèche Bas"></span>
        </div>

    </div>
    <!-- SLIDER END -->


    <div class="col-7 d-flex row align-items-center align-content-center">
        <p class="col-12 product-name">{{product.name}}</p>
        <div class="col-12 product-rate"><img src="{{asset('web/img/product/stars.svg')}}" alt="Nombre d'avis"><span> {{product.comments|length}} Avis</span></div>
        <p class="col-12 product-price">{{product.price}} €</p>
        <p class="col-12 product-description">{{product.description}}</p>

        <div class="col-12">
            

        <!-- CUSTOMIZE QUANTITY FIELD START-->

        <div class="input-group plus-minus-input">
            <div class="input-group-button">
                <button type="button" class="button-minus" data-quantity="minus" data-field="quantity">
                <span>-</span>
                </button>
            </div>
            <input class="input-group-field" type="number" name="quantity" value="1">
            <div class="input-group-button">
                <button type="button" class="button-plus" data-quantity="plus" data-field="quantity">
                <span>+</span>
                </button>
            </div>
        </div>

        <!-- CUSTOMIZE QUANTITY FIELD END-->

            <a class="btn-add-to-cart" href="">Ajouter au panier</a>
            <img class="social-icons" src="{{asset('web/img/product/fb.svg')}}" alt="Page Facebook BBB">
            <img class="social-icons" src="{{asset('web/img/product/insta.svg')}}" alt="Profil Instagram BBB">
        </div>
    </div>
    <!-- PRODUCT ELEMENT END -->
</div>

<!-- BODY MENU START -->


<ul class="body-menu">
    <li class="activated" data-display="to-display-1">Description</li>
    <li data-display="to-display-2">Composition</li>
    <li data-display="to-display-3">Fiche technique</li>
    <li data-display="to-display-4">Info livraison</li>
    <li data-display="to-display-5">Comment recycler vos flacons</li>
    <li data-display="to-display-6">Avis ({{product.comments|length}})</li>
</ul>

<!-- FIRST ELEMENT TO SHOW START-->
<div class="to-display-1">

    <p>{{product.description}}</p>

</div>
<!-- FIRST ELEMENT TO SHOW START-->

<!-- SECOND ELEMENT TO SHOW START-->
<div class="to-display-2">

    {% if product.composition is empty %}
        <p>La composition n'a pas été renseignée pour ce produit.</p>
    {% else %}
        <p>{{product.composition}}</p>
    {% endif %}

</div>
<!-- SECOND ELEMENT TO SHOW START-->

<!-- THIRD ELEMENT TO SHOW START-->
<div class="to-display-3">

    {% if product.technique is empty %}
        <p>La fiche technique n'a pas été renseignée pour ce produit.</p>
    {% else %}
        <p>{{product.technique}}</p>
    {% endif %}

</div>
<!-- THIRD ELEMENT TO SHOW START-->

<!-- FOURTH ELEMENT TO SHOW START-->
<div class="to-display-4">

    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum atque quis ut culpa, mollitia sequi, expedita ipsum numquam officia quo illum laudantium suscipit reprehenderit unde voluptates? Doloremque voluptate pariatur at.</p>

</div>
<!-- FOURTH ELEMENT TO SHOW START-->

<!-- FIFTH ELEMENT TO SHOW START-->
<div class="to-display-5">

    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Quis inventore doloremque dolores voluptatum molestias reprehenderit. Omnis autem neque nihil quidem minima debitis! Eaque nihil, incidunt vitae inventore sapiente quaerat libero.</p>

</div>
<!-- FIFTH ELEMENT TO SHOW START-->

<!-- SIXTH ELEMENT TO SHOW START-->
<div class="to-display-6">

    {% if product.comments|length > 0 %}

        {% for comment in product.comments %}

            <p>{{comment.user}}</p>
            <p>{{comment.note}}</p>
            <p>{{comment.content}}</p>
            <p>{{comment.publishedAt}}</p>

        {% endfor %}

    {% endif %}

    {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}

        <form action="" method="POST">
            <label class="bbb-form-label" for="comment">Ajouter un commentaire : </label>
            <input class="bbb-form-field" type="text" name="comment">
            <button class="bbb-btn-comment">Envoyer</button>
        </form>

    {% endif %}
    

</div>
<!-- SIXTH ELEMENT TO SHOW START-->

<!-- BODY MENU END -->

<script src="{{asset('web/js/body-menu.js')}}"></script>
<script src="{{asset('web/js/slider-image.js')}}"></script>
<script src="{{asset('web/js/input-number.js')}}"></script>

{% endblock %}

templates/shop/singles/subscription.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

{% endblock %}