src/Entity/Event.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Doctrine\Common\Collections\ArrayCollection;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EventRepository")
 * @Vich\Uploadable
 */
class Event
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $event_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $event_place;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="event_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     * @var \DateTime
     */
    private $updatedAt;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\EventPassed", mappedBy="events", cascade={"persist", "remove"})
     */
    private $eventPassed;

    /**
     * @ORM\Column(type="boolean")
     */
    private $state;

    /**
     * @ORM\Column(type="text")
     */
    private $annoncement;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\EventSubs", mappedBy="event")
     */
    private $eventSubs;

    public function __construct()
    {
        $this->eventSubs = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEventDate(): ?\DateTimeInterface
    {
        return $this->event_date;
    }

    public function setEventDate(?\DateTimeInterface $event_date): self
    {
        $this->event_date = $event_date;

        return $this;
    }

    public function getEventPlace(): ?string
    {
        return $this->event_place;
    }

    public function setEventPlace(?string $event_place): self
    {
        $this->event_place = $event_place;

        return $this;
    }

    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getEventPassed(): ?EventPassed
    {
        return $this->eventPassed;
    }

    public function setEventPassed(EventPassed $eventPassed): self
    {
        $this->eventPassed = $eventPassed;

        // set the owning side of the relation if necessary
        if ($this !== $eventPassed->getEvents()) {
            $eventPassed->setEvents($this);
        }

        return $this;
    }

    public function getState(): ?bool
    {
        return $this->state;
    }

    public function setState(bool $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getUpdatedAt(){
        return $this->updatedAt;
    }

    public function getAnnoncement(): ?string
    {
        return $this->annoncement;
    }

    public function setAnnoncement(string $annoncement): self
    {
        $this->annoncement = $annoncement;

        return $this;
    }

    public function __toString(){
        return $this->title;
    }

    /**
     * @return Collection|EventSubs[]
     */
    public function getEventSubs(): Collection
    {
        return $this->eventSubs;
    }

    public function addEventSub(EventSubs $eventSub): self
    {
        if (!$this->eventSubs->contains($eventSub)) {
            $this->eventSubs[] = $eventSub;
            $eventSub->addEvent($this);
        }

        return $this;
    }

    public function removeEventSub(EventSubs $eventSub): self
    {
        if ($this->eventSubs->contains($eventSub)) {
            $this->eventSubs->removeElement($eventSub);
            $eventSub->removeEvent($this);
        }

        return $this;
    }

}

src/Controller/ShopController.php
<?php

namespace App\Controller;

use App\Entity\EventSubs;
use App\Form\EventSubsType;
use App\Form\MessageMeType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\{Product,PackOffer,Subscription,Event,MessageMe,EventPassed};

class ShopController extends AbstractController
{
    /**
     * @Route("/", name="shop.home.index")
     */
    public function index()
    {
        $products = $this->getDoctrine()->getRepository(Product::class)->findTopProduct();
        $offers = $this->getDoctrine()->getRepository(PackOffer::class)->findAllHomeView();
        $events = $this->getDoctrine()->getRepository(Event::class)->findPublished();

        
        $subscriber = new EventSubs();
        
        $form = $this->createForm(EventSubsType::class,$subscriber);

        //Pour afficher un seul événement à la fois sur la page d'accueil
        isset($events[0]) ? $event = $events[0] : $event = null;
        isset($products[0]) ? $product = $products[0] : $product = null;

        $i = 0;

        //Pour limiter à 2 le nombre d'offres sur la page d'accueil
        foreach($offers as $offer){
            if($i < 2){
                $published_offers[] = $offer;
            }
            $i++;          
        }
        
        return $this->render('shop/index.html.twig', [
            'product' => $product,
            'offers' => $offers,
            'event' => $event,
            'form'=> $form->createView()
        ]);
    }

    /**
     * @Route("/products", name="shop.list.products")
     */
    public function listProducts(){
        $products = $this->getDoctrine()->getRepository(Product::class)->findPublished();

        return $this->render('shop/products.html.twig', [
            'products' => $products,
        ]);
    }

    /**
     * @Route("/offers", name="shop.list.offers")
     */
    public function listOffers(){
        $pack_offers = $this->getDoctrine()->getRepository(PackOffer::class)->findPublished();
        $subscriptions = $this->getDoctrine()->getRepository(Subscription::class)->findPublished();

        return $this->render('shop/offers.html.twig', [
            'pack_offers' => $pack_offers,
            'subscriptions'=> $subscriptions
        ]);
    }

    /**
     * @Route("/events", name="shop.list.events")
     */
    public function listEvents(Request $request, ObjectManager $manager){
        
        //Récupération des informations depuis la base de donnée
        $posts = $this->getDoctrine()->getRepository(EventPassed::class)->findAll();
        $events = $this->getDoctrine()->getRepository(Event::class)->findPublished();
        
        //Création et traitement du formulaire d'inscription aux événements

        $subscriber = new EventSubs();
        $data = $request->get('event_subs');
        
        $form = $this->createForm(EventSubsType::class,$subscriber);

        //récupération de l'url précédent
        $referer = $request->headers->get('referer');
     
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid() ){

            //Vérifier que l'utilisateur a bien choisi au moins un événement
            
            if(count($subscriber->getEvent()) !== 0)
            {
                $manager->persist($subscriber);
                $manager->flush();

                //redirection vers l'url précédent
                return $this->redirect($referer);
            }
            else{          
                $this->addFlash(
                    'notice_bad',
                    'Vous devez choisir au moins un événement.'
                );
            }

        }

        else if(isset($data)){

            $subscriber->setName($data['name']);
            $subscriber->setFirstName($data['first_name']);
            $subscriber->setEmail($data['email']['first']);

            if(isset($data['event'])){
                $i =0;
                foreach($data['event'] as $eventId){
                    $event = $this->getDoctrine()->getRepository(Event::Class)->findById($data['event'][$i]);
                    $subscriber->addEvent($event);
                    $i++;
                } 
            }

            try{
                
                $manager->persist($subscriber);
                $manager->flush();
            }
            catch(\Exception $e){
                $this->addFlash(
                    'notice_bad',
                    'Vous êtes déjà inscris à un événement.'
                );
            }

            //redirection vers l'url précédent
            return $this->redirect($referer);
        }


        return $this->render('shop/events.html.twig', [
            'events_passed' => $posts,
            'events' => $events,
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/articles", name="shop.list.articles")
     */
    public function listArticles(){

        return $this->render('shop/articles.html.twig', [
        ]);
    }

    /**
     * @Route("/whoweare", name="shop.show.whoweare")
     */
    public function whoWeAre(){

        return $this->render('shop/whoweare.html.twig', [
            'title' => "Qui sommes-nous ?",
        ]);
    }

    /**
     * @Route("/messageMe", name="shop.show.messageme")
     */
    public function messageMe(Request $request,\Swift_Mailer $mailer){

        $message = new MessageMe();

        $form = $this->createForm(MessageMeType::class, $message);

        $form->handleRequest($request);

        if( $form->isSubmitted() && $form-> isValid()){

            $manager = $this->getDoctrine()->getManager();
            $manager->persist($form->getData());
            $manager->flush();

            $mail = (new \Swift_Message('Contact Email'))
                        ->setFrom($message->getEmail())
                        ->setTo('chemseddine.saada2@gmail.com')
                        ->setBody(
                                $this->renderView(
                                'emails/messageme.html.twig',
                                ['message' => $message]
                            ),
                            'text/html'
                        );

            $mailer->send($mail);

            $this->addFlash(
                'success',
                'Votre message a bien été envoyé'
            );
            return $this->redirectToRoute('shop.show.messageme');
        }
        return $this->render('shop/contact.html.twig', [
            'form' => $form->createView(),
        ]);
    }


}

templates/shop/articles.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}


{% endblock %}

templates/shop/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}

{{ form_start(form)}}
{{ form_widget(form)}}
{{ form_end(form)}}

{% endblock %}

templates/shop/events.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block more_style %} 
    <link rel="stylesheet" href="{{asset('web/css/event-style.css')}}"> 
    <link rel="stylesheet" href="{{asset('web/css/body-menu.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/responsive-events.css')}}">
{% endblock %}  

{% block headerText %}
    <div class="d-flex text-header justify-content-center row text-center">
        <p class="header-title">événements</p>
        <p class="base-line">prends ta beauté en mains</p>
    </div> 
{% endblock %}

{% block body %}

<!-- POP-UP START -->

<div class="pop-up-container-2 pop-up-container" style="display:none;">
    <div class="mx-auto pop-up">
        <span class="pop-up-closing"><img src="{{asset('web/img/menu/burger-opened.svg')}}" alt="Croix de fermeture de la pop-up"></span>
        <p class="pop-up-title text-center">Inscription à l'événement</p>

            {{ form_start(form) }}
            <div class="d-flex row">
                {{form_errors(form.name)}}
                {{form_widget(form.name, {'attr': {'class': 'bbb-form-field mx-auto'}})}}

                {{form_errors(form.first_name)}}
                {{form_widget(form.first_name, {'attr': {'class': 'bbb-form-field mx-auto'}})}}

                {{form_errors(form.email)}}
                {{form_widget(form.email.first, {'attr': {'class': 'bbb-form-field mx-auto'}})}}

                {{form_widget(form.email.second, {'attr': {'class': 'bbb-form-field mx-auto'}})}}

                {{form_help(form.event,{'help_attr': {'class': 'bbb-form-field-help text-right'}})}}
                {{form_widget(form.event, {'attr': {'class': 'bbb-form-field-checkbox mx-auto'}})}}

                {{form_widget(form.save, {'attr': {'class': 'btn-bbb btn-text btn-form-submit'}})}}
            </div>

        {{ form_end(form) }}
    </div>
</div>

<!-- POP-UP END-->

<!-- FIRST DISPLAYED SECTION START-->
<ul class="body-menu ancre" id="ancre1">
    <li class="activated" data-display="to-display-1">Événements à venir</li>
    <li data-display="to-display-2">Historique des événements</li>
</ul>

<div class="to-display-1">
    {% for event in events  %}

        <h2>{{event.title}}</h2>
        <p class="event-description">{{event.description}}</p>
        <p class="event-date">Prévu pour le : {{event.eventDate | date('Y-m-d à H:i')}}</p>

        <div class="event-map d-flex column flex-wrap justify-content-center">

            <img class="img-fluid" src="{{asset('web/img/event/map.png')}}" alt="Carte montrant le point de rendez-vous">

            <p class="text-center annoncement">{{event.annoncement}}</p>

            <a class="btn-pop-up-2 mx-auto">
                <span class="btn-subscribe">s'inscrire</span>
            </a>

        </div>

    {% endfor %} 
</div>
<!-- FIRST DISPLAYED SECTION END-->

<!-- SECOND DISPLAYED SECTION START-->
<div class="to-display-2">

   {% for event_passed in events_passed  %}
   <div class="event-passed-element d-flex row">
        <div class="event-passed-image col-12 col-sm-12 col-md-12 col-lg-4 col-xl-4">
            <img class="img-fluid" src="{{'uploads/images/eventsPassed/' ~ event_passed.image1}}" alt="Photo prise lors de l'événement passé">
        </div>
        <div class="event-passed-info col-12 col-sm-12 col-md-12 col-lg-8 col-xl-8">
            <p class="event-passed-title">{{event_passed.events}}</p>
            <span class="event-passed-date">{{event_passed.events.eventDate |  date('d-m-Y')}}</span>
            <p class="event-passed-extract">{{event_passed.article | easyadmin_truncate(150)}}</p>
        </div>
   </div>
 
    {% endfor %} 
    
</div>
<!-- SECOND DISPLAYED SECTION END-->

<script src="{{asset('web/js/body-menu.js')}}"></script>

{% endblock %}

templates/shop/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}NailProject - Accueil{% endblock %}
{% block more_style %}
    <link rel="stylesheet" href="{{asset('web/css/index-style.css')}}"/>
    <link rel="stylesheet" href="{{asset('web/css/responsive-home.css')}}">
{% endblock %}  

{% block headerText %}

<img class="hashtag-bbb img-fluid" src="{{asset('web/img/index/hashtag.png')}}" alt="Hashtag Bon Beau Bien">

    <div class="row text-header align-items-center justify-content-center">
        <p>Le vernis des femmes qui s'engagent</p>
    </div>

{% endblock %}

{% block body %}

<h2 class="section-title ancre section-content" id="ancre1">Notre couleur de la saison</h2>
<section class="d-flex flex-wrap column section-content" > <!-- Our Products -->

    <div class="row d-flex flex-nowrap col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4">
        <a class="parallax0 parallax d-flex column justify-content-center align-items-end" href="{{path('single.show.product',{'slug':product.id})}}">
            <img class="product-element-image element-image mr-4 col-12 col-sm-12 col-md-12 col-lg-12 col-xl-8" src="{{asset('/uploads/images/products/' ~ product.image1)}}" alt="{{product.description}}">

            <div class="element-info column align-items-center col-12 col-sm-12 col-md-12 col-lg-12 col-xl-4">
                <h4 class="element-title product-element-title">{{product.name}}</h4>
                <p class="element-price product-element-price">{{product.price}} &#128;</p>
            </div>   

        </a>
    </div>
    <div class="align-self-center col-12 col-sm-12 col-md-12 col-lg-12 col-xl-8 description-home">
        <p class="p-bold product-description-bold">Restez belles et naturelles tout au long de l’automne, avec nos vernis fabriqués avec plus de 80% de matières premières d’origine naturelle et végétale.</p>
        <p class="product-description-light">POURQUOI ON AIME ? </br> La toute nouvelle formule de ce vernis couleur assure une application facile et rapide. Le capuchon du vernis couleur se retire pour accéder à un pinceau pratique et ergonomique.</p>
        <a class="see-more-products float-right" href="{{path('shop.list.products')}}">Voir plus de produits</a>
    </div>

</section> <!-- Our Products -->

<section class="section-content"> <!-- Our Packs -->
    <h2 class="section-title ancre" id="ancre2">Nos Offres</h2>
    <div class="d-flex row justify-content-between">
        {% for offer in offers %} 

            <a class="{{ 'parallax' ~ loop.index }} parallax col-xl-6 col-lg-12 col-md-12 col-sm-12 col-12 d-flex column justify-content-center align-items-end" href="#">
                
                <img class="element-image img-fluid offer-element-image col-xl-8 col-lg-12 col-md-12 col-sm-12 col-12 mr-4" src="{{asset('/uploads/images/packOffers/' ~ offer.image1)}}" alt="{{offer.description}}">

                <div class="element-info column align-items-center col-xl-4 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h4 class="element-title offer-element-title">{{offer.name}}</h4>
                    {% for product in offer.products  %}
                        <p class="element-price offer-products offer-element-price">Notre {{product.name}}</p>
                    {% endfor %}
                    <p class="element-price offer-element-price">{{offer.price}} &#128;</p>
                </div>
                
            </a>

        {% endfor %}
    </div>
</section> <!-- Our Packs -->

<section> <!-- Our Subscription -->

    <h2 class="section-title ancre section-content" id="ancre3">Événements</h2>
    <div class="div-for-background">
        <div class="event-element d-flex d-table-row section-content">

            {% if event is null %}
                <p>Nous n'avons aucun événement futur pour l'instant, abonnez-vous à notre Newsletter pour recevoir les dates dès leurs publications !</p>
            {% else %}

            <div class="event-map-index d-flex row flex-wrap justify-content-between align-items-center">
                <div class="map col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6 ">
                    <img class="img-fluid" src="{{asset('web/img/event/map.png')}}" href="Carte montrant le lieu de l'événement">
                </div>

                <div class="col-12 col-sm-12 col-md-12 col-lg-12 col-xl-6">
                    <div class="event-text">
                        <p class="annoncement">{{ event.annoncement }}</p>
                        <div class="d-flex justify-content-between align-content-center align-items-center">
                            <a class="align-self-center mr-3" href="#"><img src="{{asset('/web/img/whoweare/share.svg')}}" alt="Boutton de partage sur les réseaux sociaux"></a>
                            <a class="btn-pop-up-2 btn-subscribe" href="#">s'inscrire</a>
                        </div>                     
                    </div>                    
                </div>
            </div>
        </div>
    </div>
    {% endif %}

    <!-- POP-UP START -->

    <div class="pop-up-container-2 pop-up-container" style="display:none;">
        <div class="mx-auto pop-up">
            <span class="pop-up-closing"><img src="{{asset('web/img/menu/burger-opened.svg')}}" alt="Croix de fermeture de la pop-up"></span>
            <p class="pop-up-title text-center">Inscription à l'événement</p>
    
            <form action="{{path('shop.list.events')}}" method="POST">
                <div class="d-flex row">
                    {{form_errors(form.name)}}
                    {{form_widget(form.name, {'attr': {'class': 'bbb-form-field mx-auto'}})}}
    
                    {{form_errors(form.first_name)}}
                    {{form_widget(form.first_name, {'attr': {'class': 'bbb-form-field mx-auto'}})}}
    
                    {{form_errors(form.email)}}
                    {{form_widget(form.email.first, {'attr': {'class': 'bbb-form-field mx-auto'}})}}
    
                    {{form_widget(form.email.second, {'attr': {'class': 'bbb-form-field mx-auto'}})}}
    
                    {{form_help(form.event,{'help_attr': {'class': 'bbb-form-field-help text-right'}})}}
                    {{form_widget(form.event, {'attr': {'class': 'bbb-form-field-checkbox mx-auto'}})}}
    
                    {{form_widget(form.save, {'attr': {'class': 'btn-bbb btn-text btn-form-submit'}})}}
                </div>
    
            </form>
        </div>
    </div>
    
    <!-- POP-UP END-->

</section> <!-- Our Subscription -->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="{{asset('web/js/home-anime.js')}}"></script>
<script src="{{asset('web/js/footer-anime.js')}}"></script>


{% endblock %}

templates/shop/offers.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}


{% endblock %}

templates/shop/products.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block more_style %}
    <link rel="stylesheet" href="{{asset('web/css/product-style.css')}}"/>
    <link rel="stylesheet" href="{{asset('web/css/responsive-products.css')}}">
{% endblock %}  

{% block headerText %}
    <div class="d-flex text-header-products text-header justify-content-center row text-center">
        <p class="header-title">Nos produits</p>
        <p class="base-line">la beauté au bout des doigts</p>
    </div> 
{% endblock %}

{% block body %}
    <div class="row justify-content-between ancre"  id="ancre1">
        <p class="product-number-displayer"><span class="product-number">{{products|length}}</span> produits</p>

        <form action="" method="GET" class="product-filter">
            <select id="product-list-filter">
                <option value="all" selected>Tous</option>
                <option value="polish">Vernis</option>
                <option value="coat">Coat</option>
            </select>
        </form>
    </div>

    <div class="d-flex row justify-content-between">
    {% for product in products  %}


        <div class="product-element col-12 col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-3   ">
 
            <div class="product-image-container">
                <div class="hover-effect d-flex text-center align-items-center">
                    <a {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                            class="add-to-cart add-tocart  add-to-cart-btn"
                        {% else %}            
                            class="add-to-cart add-tocart btn-pop-up-1" 
                        {% endif %}

                        product-id="{{product.id}}"
                        >Ajouter au panier</a>
                </div>
                <img class="mx-auto img-fluid product-image" src="{{asset('/uploads/images/products/' ~ product.image1)}}" alt="{{product.description}}">
            </div>
            
            <div class="product-info column">
                <div class="justify-content-between d-flex">
                    <p class="product-type">{{product.type}}</p>
                    <p class="product-category text-right">{{product.category}}</p>                                 
                </div>
                <div class="justify-content-between d-flex">                
                    <a href="{{path('single.show.product',{'slug':product.id})}}" class="product-name">{{product.name}}</a> 
                    <p class="product-price text-right">{{product.price}} &#128;</p>
                </div>        
            </div>

        </div>
    {% endfor %}
    </div>

    <script>
        $(document).ready(function(){
            $('.hover-effect').mouseenter(function (e) { 
                $(e.target).css('opacity','1');
            });

            $('.hover-effect').mouseleave(function (e) { 
                $('.hover-effect').css('opacity','0');
            });


            
            $('.product-image-container').mouseleave(function (e) { 
                $('.hover-effect').css('opacity','0');
            });

            $('.product-image').mouseleave(function (e) { 
                $('.hover-effect').css('opacity','0');
            });

        });
    </script>
{% endblock %}

templates/shop/whoweare.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block more_style %} 
    <link rel="stylesheet" href="{{asset('web/css/whoweare-style.css')}}"> 
    <link rel="stylesheet" href="{{asset('web/css/body-menu.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/slick.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/slick-theme.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/responsive-whoweare.css')}}">
{% endblock %}  

{% block headerText %}
    <div class="d-flex text-header justify-content-center row text-center">
        <p class="header-title">#Bon<span style="color:red;">B</span>eauBien</p>
        <p class="base-line">je choisis une beauté engagée</p>
    </div> 
{% endblock %}

{% block body %}

<!-- BODY MENU START -->
<ul class="body-menu ancre" id="ancre1">

    <li class="activated" data-display="to-display-1">Pourquoi BBB ?</li>
    <li data-display="to-display-2">Nos valeurs</li>
    <li data-display="to-display-3">Nos engagements</li>

</ul>
<!-- BODY MENU END -->

<!-- FIRST ELEMENT TO DISPLAY -->
<div class="to-display-1">

    <div class="video-container">
        <iframe src="https://www.youtube.com/embed/rxB-m3VWYZM"
                frameborder="0" 
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture;" 
                allowfullscreen></iframe>
    </div>

    <p class="paragraph">Ce qui anime de nombreuses start up de la beauté aujourd’hui, c’est l’envie de proposer une alternative moins pétrochimique, plus bio et plus clean à une cosmétique traditionnelle qui ne fait plus trop rêver. C’est bien, mais certaines personnes ont une vision, qui dépasse l’univers cosmétique. Elles veulent s’EN-GA-GER !</p>
    <h2 class="text-center">Nos ambassadrices</h2>

    <!-- VIDEO SLIDER START -->

    <div class="slider-video">
        <div>
            <video preload='auto' data-setup='{}' play>
                <source src="{{asset('web/video/vid1.mp4')}}"
                type="video/mp4">
             </video>
        </div>
        <div>
            <video preload='auto' data-setup='{}'>
                <source  src="{{asset('web/video/vid2.mp4')}}"
                type="video/mp4">
            </video>
        </div>
        <div>
            <video preload='auto' data-setup='{}'>
                <source src="{{asset('web/video/vid3.mp4')}}"
                type="video/mp4">
            </video>
        </div>
    </div>

    <!-- VIDEO SLIDER END -->

    <!-- SHARE BUTTON START -->
    <div class="div-share d-flex justify-content-center">

        <a class="text-center text-share" href="#">
        <img src="{{asset('web/img/whoweare/share.svg')}}" alt="Boutton de partage sur les réseaux sociaux">
        Partagez</a>

    </div>
    <!-- SHARE BUTTON END -->

</div>
<!-- FIRST ELEMENT TO DISPLAY END -->


<!-- SECOND ELEMENT TO DISPLAY -->
<div class="to-display-2">

    <h2>Nos valeurs</h2>
    <p class="paragraph">Lorem ipsum dolor, sit amet consectetur adipisicing elit. A dolorem, esse doloribus perferendis enim magni amet officia dolores ipsa voluptatum? Ad illo beatae culpa ipsa officia cum iure minima nam.</p>

</div>
<!-- SECOND ELEMENT TO DISPLAY END-->

<!-- THIRD ELEMENT TO DISPLAY -->
<div class="to-display-3">

    <h2>Nos engagements</h2>
    <p class="paragraph">Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus hic et laborum voluptatem voluptatum odit voluptates officiis accusantium. Dolor officia labore cupiditate aspernatur quidem ut nam molestiae asperiores voluptatibus omnis.</p>

</div>
<!-- THIRD ELEMENT TO DISPLAY END-->

<script src="{{asset('web/js/body-menu.js')}}"></script>
<script src="{{asset('web/js/slick.min.js')}}"></script>
<script src="{{asset('web/js/slider-video.js')}}"></script>

{% endblock %}