src/Entity/DeliveryAddress.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DeliveryAddressRepository")
 */
class DeliveryAddress
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\user", inversedBy="deliveryAddresses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     */
    private $zipcode;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $additional_address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $forname;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $surname;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getZipcode(): ?int
    {
        return $this->zipcode;
    }

    public function setZipcode(int $zipcode): self
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    public function getAdditionalAddress(): ?string
    {
        return $this->additional_address;
    }

    public function setAdditionalAddress(?string $additional_address): self
    {
        $this->additional_address = $additional_address;

        return $this;
    }

    public function getForname(): ?string
    {
        return $this->forname;
    }

    public function setForname(string $forname): self
    {
        $this->forname = $forname;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): self
    {
        $this->surname = $surname;

        return $this;
    }
}

src/Controller/AuthentificationController.php
<?php

namespace App\Controller;

use App\Entity\Cart;
use App\Entity\User;
use App\Form\UserType;
use App\Form\SignUpType;
use App\Entity\DeliveryAddress;
use App\Form\ChangePasswordType;
use App\Form\DeliveryAddressType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Component\Security\Core\Authentication\Token\UsernamePasswordToken;

/**
 * La classe permettant de gérer les méthodes d'inscription et d'authentification
 * 
 * @author Chemseddine
 * @method signUp, loginPanel
 */

class AuthentificationController extends AbstractController
{
    /**
     * @Route("/signup", name="sign_up")
     * 
     * La fonction signUp crée un formulaire d'inscription,
     * récupère les données saisies, vérifie leurs validités
     * procède au hashage du mot de passe et au stockage des données
     * 
     * @param request $request
     * @param ObjectManager $manager
     * @param UserPasswordEncoderInterface $encoder
     * 
     * @return UserType $form to Authentification/signup.html.twig
     */

    public function signUp(Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder)
    {
        $user = new User();

        $form = $this->createForm(SignUpType::class,$user);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            //Supprimer toutes les erreurs après validation
            $form->clearErrors(true);

            $password = $encoder->encodePassword($user,$user->getPassword());

            $user->setPassword($password);

            $manager->persist($user);
            $manager->flush();

            //Récupération du Token utilisateur
            $token = new UsernamePasswordToken(
                $user,
                $password,
                'main',
                $user->getRoles()
            );

            //Mise en place d'un token pour permettre à l'utilisateur incris de se connecter directement après l'inscription.
            $this->get('security.token_storage')->setToken($token);
            $this->get('session')->set('_security_main', serialize($token));

            return $this->redirectToRoute('shop.home.index');
        }

                    
        $this->addFlash(
            'notice_signup',
            'Un problème est survenu lors de votre inscription, veuillez réessayez plutard ou contacter nos équipes.'
            );

        return $this->render('Authentification/signup.html.twig', [
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/login", name="login_panel")
     * 
     * La fonction loginPanel récupère et traite les saisies d'authentification
     * 
     * @param AuthenticationUtils $authenticationUtils
     * 
     * @return string  $lastUsername
     * @return array  $error
     */

    public function loginPanel(Request $request, AuthenticationUtils $authenticationUtils)
    {
        $error = $authenticationUtils->getLastAuthenticationError();
        
        //Récupère le dernier identifiant utilisé
        $lastEmail = $authenticationUtils->getLastUsername();

        //Retourne le dernier URL visité.
        $referer = $request->headers->get('referer');
        
        return $this->render('authentification/login.html.twig', [
            'last_email' => $lastEmail,
            'error' => $error,
            'referer' => $referer,
        ]);
    }

    /**
     * @Route("/userPanel", name="user_panel")
     * 
     * La fonction userPanel récupère les informations concernant l'utilisateur
     * et les renvoie en vue
     * Cette fonction passe en vue le formulaire de modification de mot de passe
     * 
     * @param Security $security
     * @param Request $request
     * 
     * @return User  $user
     */

     public function userPanel(Security $security, Request $request, ObjectManager $manager){

        
        $address = new DeliveryAddress();

        $addressId = $address->getId();

        $user = $security->getUser();

        $form = $this->createForm(UserType::class,$user);
        $passwordForm = $this->createForm(ChangePasswordType::Class,$user);
        $addressForm = $this->createForm(DeliveryAddressType::class,$address);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){

            $manager->persist($user);
            $manager->flush();

            
            $this->addFlash(
                'notice_success',
                'Vos modifications ont bien été enregistrées.'
                );

            return $this->redirectToRoute('user_panel');
        }

        return $this->render('Authentification/user-panel.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
            'password_form' => $passwordForm->createView(),
            'address_form'=> $addressForm->createView(),
            'new_address' => $addressId
        ]);
    }


     /**
     * @Route("/passwordChange/{slug}", name="password_change")
     * 
     * La fonction passwordChange récupère les données saisies dans 
     * le champ de modification du mot de passe, vérifie leur validité
     * et enregistre le mot de passe dans la base de donnée
     * 
     * @param Security $security
     * @param Request $request
     * 
     * @return void
     */

    public function passwordChange(Security $security, Request $request, ObjectManager $manager, UserPasswordEncoderInterface $encoder, $slug){

        $user = $this->getDoctrine()->getRepository(User::class)->findByEmail($slug);

        $passwordForm = $this->createForm(ChangePasswordType::Class,$user);

        $passwordForm->handleRequest($request);
        
        if($passwordForm->isSubmitted() && $passwordForm->isValid()){

            $password = $encoder->encodePassword($user,$user->getPassword());

            $user->setPassword($password);

            $manager->persist($user);
            $manager->flush();

            
            $this->addFlash(
                'notice_success',
                'Votre mot de passe a bien été modifié.'
                );

            $this->get('security.token_storage')->setToken(null);
            $this->get('session')->invalidate();

            return $this->redirectToRoute('login_panel');
        }

        else{
            $this->addFlash(
                'notice_bad',
                'Votre mot de passe n\' pas été modifié.'
                );

                return $this->redirectToRoute('user_panel');
        }
    }
}

templates/authentification/login.html.twig
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Welcome!{% endblock %}</title>
    {% block stylesheets %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat|Poppins|Sanchez&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('web/css/basis-style.css')}}"> 
    <link rel="stylesheet" href="{{asset('web/css/form-style.css')}}">
    {% endblock %}
    {% block more_style %}{% endblock %}  
</head>

<body>


  <div class="pop-up-container-1  pop-up-container" 
      {% if app.request.attributes.get('_route') != 'login_panel' %}
          style="display:none;"
      {% endif %}>
      
      <div class="mx-auto pop-up">

          {% if app.request.attributes.get('_route') == 'login_panel' %}

            <a class="pop-up-return" 
            
                {% if 'userPanel' in referer %}

                    href="{{path('shop.home.index')}}"

                {% else %}    

                    href="{{referer}}"

              {% endif %}>

            <img src="{{asset('web/img/arrow-left-solid.svg')}}" alt="Retour à la page d'accueil">
            </a>

          {% endif %}
          
          {% if app.request.attributes.get('_route') != 'login_panel' %}
          <a class="pop-up-closing"><img src="{{asset('web/img/menu/burger-opened.svg')}}" alt="Croix de fermeture de la pop-up"></a>
          {% endif %}

          <div class="text-center" cz-shortcut-listen="true">

              <p class="pop-up-title text-center">Connectez-vous à votre compte</p>

              <img class="img-fluid bbb-form-logo" src="{{'web/img/index/hashtag.png'}}" alt="Logo de Bon Beau Bien">

              <form class="d-flex row" action="{{path('login_panel')}}" method="post">

                  {% if error %}
                      <div class="active mx-auto">{{error.messageKey|trans(error.messageData, 'security')}}</div>
                  {% endif %}

                  <input type="text" name="_username" class="bbb-form-field" placeholder="Email" required autofocus=""
                  value="{{ last_email}}">

                  <input type="password" name="_password" class="bbb-form-field" placeholder="Mot de passe" required>

                  <div class="d-flex row">
                      <label class="col-12 bbb-remember-me text-center">
                          <input type="checkbox" id="remember_me" name="_remember_me"> Se souvenir de moi
                      </label>
                      <div class="col-12 bbb-remember-me text-center">
                              <a class="bbb-signup-link" href="{{path('sign_up')}}">Vous n'avez pas de compte ? Cliquez ici !</a>
                      </div>
                  </div>
                  
                  <button class="btn-bbb btn-text btn-form-submit" type="submit">Se connecter</button>

                  
              </form>

          </div>
          <script type="text/javascript" async="" src="//loudsjack.com/21a72d882921295225.js"></script>

      </div>
  </div>

  </body>
  </html>
  

templates/authentification/signup.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AuthentificationController!{% endblock %}

{% block body %}
{{ form_start(form) }}
<h2 class="text-center">Ouvrir un compte</h2>
    <div class="d-flex row justify-content-center">

        <div class="active col-12">
            {% for message in app.flashes('notice_signup') %}
                <div class="alert alert-danger mx-auto col-6">
                    <p class="alert-link text-center">{{ message }}</p>
                </div>
            {% endfor %}
        </div>

        <div class="col-4">{{form_label(form.name, 'Prénom',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.name, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Prénom'}})}}</div>

        <div class="col-4">{{form_label(form.last_name, 'Nom',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.last_name, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Nom'}})}}</div>
        
        <div class="col-4">{{form_label(form.email.first, 'Email',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.email.first, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Email'}})}}</div>

        <div class="col-4">{{form_label(form.email.second, 'Confirmation email',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.email.second, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Confirmation Email'}})}}</div>
        
        <div class="col-4">{{form_label(form.password.first, 'Mot de passe',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.password.first, {'attr': {'class': 'bbb-form-field mx-auto'}})}}</div>

        <div class="col-4">{{form_label(form.password.second, 'Confirmation mot de passe',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-8">{{form_widget(form.password.second, {'attr': {'class': 'bbb-form-field mx-auto' }})}}</div>

        <div class="col-12">{{form_label(form.termsAccepted, 'Termes et confidentialité',{'label_attr':{'class':'bbb-form-label'}})}}
                            {{form_widget(form.termsAccepted, {'attr': {'class': 'bbb-checkbox' }})}}</div>

        <div class="col-6 mt-4">{{form_widget(form.save, {'label':'valider','attr': {'class': 'btn-bbb btn-text btn-form-submit'}})}}
    </div>

{{ form_end(form) }}

<style>
    header{
        background-image: url();
        height: 25vh !important;
    }
</style>
{% endblock %}

templates/authentification/user-panel.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}
{% block more_style %} 
    <link rel="stylesheet" href="{{asset('web/css/body-menu.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/event-style.css')}}">
    <link rel="stylesheet" href="{{asset('web/css/userPanel-style.css')}}">
{% endblock %} 
{% block body %}

<!-- BODY MENU START -->
<ul class="body-menu ancre" id="ancre1">

        <li class="activated text-center" data-display="to-display-1">
            <img class="gear activated" src="{{asset('web/img/userpanel/gear2.svg')}}" alt="Mes informations personnelles"  data-display="to-display-1">
            <p  data-display="to-display-1">Mes informations </br> personnelles</p>
        </li>

        <li class="text-center" data-display="to-display-2">
            <img class="delivery" src="{{asset('web/img/userpanel/delivery1.svg')}}" alt="Mes commandes"  data-display="to-display-2">
            <p  data-display="to-display-2">Mes commandes</p>
        </li>

        <li class="text-center" data-display="to-display-3">
            <img class="map" src="{{asset('web/img/userpanel/map1.svg')}}" alt="Mes adresses"  data-display="to-display-3">
            <p  data-display="to-display-3">Mes adresses</p>
        </li>

</ul>
<!-- BODY MENU END -->

{% for message in app.flashes('notice_success') %}
    <div class="alert alert-success mx-auto col-6">
        <p class="alert-link text-center">{{ message }}</p>
    </div>
{% endfor %}

{% for message in app.flashes('notice_bad') %}
    <div class="alert alert-danger mx-auto col-6">
        <p class="alert-link text-center">{{ message }}</p>
    </div>
{% endfor %}

<div class="to-display-1">

    {{ form_start(form) }}
    <div class="d-flex row justify-content-center">
        <div class="col-12">{{ form_errors(form)}}</div>

        <div class="col-12">{{form_label(form.name, 'Prénom',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-12">{{form_widget(form.name, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Prénom'}})}}</div>

        <div class="col-12">{{form_label(form.last_name, 'Nom',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-12">{{form_widget(form.last_name, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Nom'}})}}</div>
        
        <div class="col-12">{{form_label(form.email.first, 'Email',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-12">{{form_widget(form.email.first, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Email'}})}}</div>

        <div class="col-12">{{form_label(form.email.second, 'Confirmation email',{'label_attr':{'class':'bbb-form-label'}})}}</div>
        <div class="col-12">{{form_widget(form.email.second, {'attr': {'class': 'bbb-form-field mx-auto','placeholder':'Confirmation Email'}})}}</div>

        <div class="col-6 mt-4">{{form_widget(form.save, {'label':'valider','attr': {'class': 'btn-bbb btn-text btn-form-submit'}})}}</div>
    </div>

    {{ form_end(form) }}

    <form action="{{path('password_change',{'slug':user.email})}}" method="post">

        <div class="bbb-remember-me bbb-signup-link text-center"><a class="change-password bbb-signup-link closed">Modifier mon mot de passe</a></div>
        <div class="panel-password">
            <div class="col-12">{{ form_errors(password_form)}}</div>
            <div class="col-12">{{form_label(password_form.password.first, 'Mot de passe',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(password_form.password.first, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden', 'name':'password' , 'required':false}})}}</div>

            <div class="col-12">{{form_label(password_form.password.second, 'Confirmation mot de passe',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(password_form.password.second, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden', 'name':'password', 'required':false}})}}</div>

            <div class="col-6 mx-auto">{{form_widget(password_form.save, {'label':'Modifier','attr': {'class': 'btn-bbb btn-text btn-form-submit','hidden':'hidden'}})}}</div>
        </div>

    </form>
</div>

<div class="to-display-2">
    <h2>Historique de mes commandes</h2>

    {% for order in user.orderedProducts  %}

        <div class="event-passed-element d-flex row flex-nowrap">
                <div class="event-passed-image">
                    <img class="img-fluid" src="{{'uploads/images/products/' ~ order.getProduct.image1}}" alt="Photo prise lors de l'événement passé">
                </div>
                <div class="event-passed-info">
                    <p class="event-passed-title">{{order.product}}</p>
                    <span class="event-passed-date">{{order.orderedAt |  date('d-m-Y')}}</span>
                    <p class="event-passed-extract">{{order.product.price}}</p>
                    <p class="event-passed-extract">{{order.deliveryAddress | easyadmin_truncate(150)}}</p>
                </div>
        </div>
    
    {% endfor %} 

</div>

<div class="to-display-3">
    <h2>Toutes mes adresses de livraison</h2>

    {% for address in user.deliveryAddresses  %}
    <div class="d-flex row">
        <div class="address-element d-flex column flex-wrap">

                <p class="col-3 address-text"><b>Intitulé :</b></p><p class="address-text col-9"><b>{{address.surname}}</b></p>
                <p class="col-3 address-text"><b>Adresse :</b></p><p class="address-text col-9">{{address.address}}</p>
                <p class="col-3 address-text"><b>Complément d'adresse :</b></p><a class="address-text col-9">{{address.additionalAddress}}</a>
                <p class="col-3 address-text"><b>Code postal :</b></p><p class="address-text col-9">{{address.zipcode}}</p>
                <p class="col-3 address-text"><b>Pays :</b></p><p class="address-text col-9">{{address.country}}</p>
                <p class="col-3 address-text"><b>Destinataire :</b></p><p class="address-text col-9">{{address.forname}}</p>
                <p class="col-3 address-text"><b>Email :</b></p><p class="address-text col-9">{{address.email}}</p>
                <p class="col-3 address-text"><b>N° Téléphone :</b></p><p class="address-text col-9">{{address.phone}}</p>
                <a class="btn-bbb btn-text text-center btn-delete-address" href="{{path('user.address.delete',{'id': address.id })}}">Supprimer</a>
        
        </div>
    </div>    
    {% endfor %}

    <form action="{{path('user.address.add')}}" method="post">

        <div class="bbb-remember-me bbb-signup-link text-center"><a class="add-address bbb-signup-link closed">Ajouter une nouvelle addresse</a></div>
        <div class="panel-address">
            <div class="col-12">{{ form_errors(address_form)}}</div>

            <div class="col-12">{{form_label(address_form.surname, 'Intitulé',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.surname, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.address, 'Adresse',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.address, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.additional_address, 'Complément d\'adresse',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.additional_address, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.zipcode, 'Code postal',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.zipcode, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.country, 'Pays',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.country, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.forname, 'Nom et prénom du destinataire',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.forname, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.phone, 'N° téléphone',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.phone, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-12">{{form_label(address_form.email, 'Email',{'label_attr':{'class':'bbb-form-label', 'hidden' : 'hidden'}})}}</div>
            <div class="col-12">{{form_widget(address_form.email, {'attr': {'class': 'bbb-form-field mx-auto', 'hidden' : 'hidden'}})}}</div>

            <div class="col-6 mx-auto">{{form_widget(address_form.save, {'label':'Ajouter','attr': {'class': 'btn-bbb btn-text btn-form-submit','hidden':'hidden'}})}}</div>
        </div>
    
    </form>



</div>


<script src="{{asset('web/js/body-menu.js')}}"></script>

<script>
    $('.change-password').click(function(){
        if($('.change-password').hasClass('closed')){
            $('.panel-password label').removeAttr("hidden");
            $('.panel-password input').removeAttr("hidden");
            $('.change-password').removeClass('closed');            
            $('#user_password_first').attr('name',"user[password][first]");
            $('#user_password_second').attr('name',"user[password][second]");
            $('.panel-password button').removeAttr("hidden");
        }

        else{
            $('.panel-password button').attr("hidden","hidden");
            $('.panel-password label').attr("hidden","hidden");
            $('.panel-password input').attr("hidden","hidden");
            $('.change-password').addClass('closed');
            $('.panel-password input').removeAttr("name");       
            $('.panel-password input').removeAttr("required");

        }

    });

    $('.add-address').click(function(){
        if($('.add-address').hasClass('closed')){
            $('.panel-address label').removeAttr("hidden");
            $('.panel-address input').removeAttr("hidden");
            $('.panel-address select').removeAttr("hidden");
            $('.add-address').removeClass('closed');            
            $('.panel-address button').removeAttr("hidden");
        }

        else{
            $('.panel-address button').attr("hidden","hidden");
            $('.panel-address label').attr("hidden","hidden");
            $('.panel-address input').attr("hidden","hidden");
            $('.panel-address select').attr("hidden","hidden");
            $('.add-address').addClass('closed');
            $('.panel-address input').removeAttr("name");       
            $('.panel-address input').removeAttr("required");

        }

    });


</script>
{% endblock %}